"""Offline structured reasoning contracts."""

from axq.reasoning.contracts import (
    BoundedReasoningContextItem,
    LLMAttemptStatus,
    LLMExecutionAttemptAudit,
    LLMFailureCode,
    LLMFailureMetadata,
    LLMGenerationPolicy,
    LLMRequestEnvelope,
    LLMReusePolicy,
    LLMStructuredResponseArtifact,
    PromptTemplateIdentity,
    ProviderKind,
    ProviderModelIdentity,
    ReasoningRunResult,
    ReasoningSourceKind,
    ReasoningSourceReference,
    ReasoningTask,
    ReflectionExplanation,
    ReflectionExplanationInput,
    UncertaintyAssessment,
    UncertaintyLevel,
    canonical_reasoning_bytes,
)
from axq.reasoning.ollama import (
    OllamaHTTPTransport,
    OllamaProvider,
    OllamaTransport,
    validate_loopback_ollama_url,
)
from axq.reasoning.prompts import (
    RenderedReasoningPrompt,
    reflection_explanation_prompt_identity,
    render_reflection_explanation_prompt,
)
from axq.reasoning.provider import (
    LLMInvalidProviderResponseError,
    LLMModelIdentityMismatchError,
    LLMModelUnavailableError,
    LLMProvider,
    LLMProviderConnectionError,
    LLMProviderError,
    LLMProviderTimeoutError,
    ProviderAttemptControls,
    ProviderCompletion,
    ProviderUsage,
)
from axq.reasoning.service import (
    build_reflection_explanation_request,
    run_reflection_explanation,
)
from axq.reasoning.store import SQLiteReasoningAuditStore

__all__ = [
    "BoundedReasoningContextItem",
    "LLMAttemptStatus",
    "LLMExecutionAttemptAudit",
    "LLMFailureCode",
    "LLMFailureMetadata",
    "LLMGenerationPolicy",
    "LLMInvalidProviderResponseError",
    "LLMModelIdentityMismatchError",
    "LLMModelUnavailableError",
    "LLMProvider",
    "LLMProviderConnectionError",
    "LLMProviderError",
    "LLMProviderTimeoutError",
    "LLMRequestEnvelope",
    "LLMReusePolicy",
    "LLMStructuredResponseArtifact",
    "OllamaHTTPTransport",
    "OllamaProvider",
    "OllamaTransport",
    "PromptTemplateIdentity",
    "ProviderAttemptControls",
    "ProviderCompletion",
    "ProviderKind",
    "ProviderModelIdentity",
    "ProviderUsage",
    "RenderedReasoningPrompt",
    "ReasoningRunResult",
    "ReasoningSourceKind",
    "ReasoningSourceReference",
    "ReasoningTask",
    "ReflectionExplanation",
    "ReflectionExplanationInput",
    "UncertaintyAssessment",
    "UncertaintyLevel",
    "SQLiteReasoningAuditStore",
    "canonical_reasoning_bytes",
    "build_reflection_explanation_request",
    "reflection_explanation_prompt_identity",
    "render_reflection_explanation_prompt",
    "run_reflection_explanation",
    "validate_loopback_ollama_url",
]
