"""Deterministic Phase 8 reflection contracts and services."""

from axq.reflection.candidate_replay_contracts import (
    CandidateReplayArtifactRef,
    CandidateReplayAudit,
    CandidateReplayEngineKind,
    CandidateReplayRequest,
    CandidateReplayStatus,
    ControlledMetricValue,
    ControlledReplayFixtureArtifact,
    ControlledReplayObservation,
)
from axq.reflection.candidate_replay_engine import (
    CandidateReplayEngine,
    CandidateReplayEngineOutput,
    ControlledReplayFixtureEngine,
)
from axq.reflection.candidate_replay_service import (
    CandidateReplayOutcome,
    execute_candidate_replay,
)
from axq.reflection.candidate_replay_store import SQLiteCandidateReplayStore
from axq.reflection.contracts import (
    DailyReflection,
    FindingCategory,
    FindingSignal,
    MetricFact,
    ReflectionFinding,
    ReflectionPolicy,
    SampleGuardRecord,
    SampleGuardStatus,
)
from axq.reflection.daily import build_daily_reflection
from axq.reflection.evaluation_contracts import (
    AcceptanceCriterion,
    CandidateKind,
    CriterionComparator,
    CriterionOutcome,
    CriterionOutcomeStatus,
    CriterionRole,
    EvaluationAggregateOutcome,
    EvaluationCandidateSpec,
    FinalOOSPolicy,
    MetricDirection,
    MetricObservation,
    MetricObservationStatus,
    MetricScope,
    OperatorEvaluationDecision,
    OperatorEvaluationDecisionKind,
    ProposalEvaluationPlan,
    ProposalEvaluationResult,
    SemanticArtifactRef,
    ValidationMetricSpec,
)
from axq.reflection.evaluation_store import SQLiteProposalEvaluationStore
from axq.reflection.evaluations import build_evaluation_plan, build_evaluation_result
from axq.reflection.execution_contracts import (
    CanonicalMetricSampleArtifact,
    EvaluationAdapterKind,
    EvaluationExecutionAudit,
    EvaluationExecutionRequest,
    EvaluationExecutionStatus,
    ExecutionInputArtifactRef,
    MetricSampleSeries,
)
from axq.reflection.execution_service import (
    EvaluationExecutionOutcome,
    execute_evaluation_request,
)
from axq.reflection.execution_store import SQLiteEvaluationExecutionStore
from axq.reflection.proposal_contracts import (
    ImprovementProposal,
    ImprovementProposalPolicy,
    ProposalEvidenceGuard,
    ProposalGuardKind,
    ProposalStatus,
    ProposalStatusTransition,
    ProposalTargetComponent,
)
from axq.reflection.proposal_store import SQLiteImprovementProposalStore
from axq.reflection.proposals import (
    ProposalBuildResult,
    ProposalEligibilityAssessment,
    build_improvement_proposals,
)
from axq.reflection.store import SQLiteReflectionStore
from axq.reflection.weekly import build_weekly_reflection
from axq.reflection.weekly_contracts import (
    FailurePattern,
    KnowledgeStatus,
    PatternMetricSummary,
    PatternSignalClass,
    PatternStatusTransition,
    PatternType,
    SuccessPattern,
    TransitionActionKind,
    WeeklyGuardKind,
    WeeklyReflection,
    WeeklyReflectionPolicy,
    WeeklySampleGuard,
)
from axq.reflection.weekly_store import SQLiteWeeklyReflectionStore

__all__ = [
    "CandidateReplayArtifactRef",
    "CandidateReplayAudit",
    "CandidateReplayEngineKind",
    "CandidateReplayRequest",
    "CandidateReplayStatus",
    "ControlledMetricValue",
    "ControlledReplayFixtureArtifact",
    "ControlledReplayObservation",
    "CandidateReplayEngine",
    "CandidateReplayEngineOutput",
    "ControlledReplayFixtureEngine",
    "CandidateReplayOutcome",
    "execute_candidate_replay",
    "SQLiteCandidateReplayStore",
    "DailyReflection",
    "FindingCategory",
    "FindingSignal",
    "MetricFact",
    "ReflectionFinding",
    "ReflectionPolicy",
    "SampleGuardRecord",
    "SampleGuardStatus",
    "build_daily_reflection",
    "SQLiteReflectionStore",
    "AcceptanceCriterion",
    "CandidateKind",
    "CriterionComparator",
    "CriterionOutcome",
    "CriterionOutcomeStatus",
    "CriterionRole",
    "EvaluationAggregateOutcome",
    "EvaluationCandidateSpec",
    "FinalOOSPolicy",
    "MetricDirection",
    "MetricObservation",
    "MetricObservationStatus",
    "MetricScope",
    "OperatorEvaluationDecision",
    "OperatorEvaluationDecisionKind",
    "ProposalEvaluationPlan",
    "ProposalEvaluationResult",
    "SemanticArtifactRef",
    "ValidationMetricSpec",
    "SQLiteProposalEvaluationStore",
    "build_evaluation_plan",
    "build_evaluation_result",
    "CanonicalMetricSampleArtifact",
    "EvaluationAdapterKind",
    "EvaluationExecutionAudit",
    "EvaluationExecutionRequest",
    "EvaluationExecutionStatus",
    "ExecutionInputArtifactRef",
    "MetricSampleSeries",
    "EvaluationExecutionOutcome",
    "execute_evaluation_request",
    "SQLiteEvaluationExecutionStore",
    "ImprovementProposal",
    "ImprovementProposalPolicy",
    "ProposalEvidenceGuard",
    "ProposalGuardKind",
    "ProposalStatus",
    "ProposalStatusTransition",
    "ProposalTargetComponent",
    "SQLiteImprovementProposalStore",
    "ProposalBuildResult",
    "ProposalEligibilityAssessment",
    "build_improvement_proposals",
    "FailurePattern",
    "KnowledgeStatus",
    "PatternMetricSummary",
    "PatternSignalClass",
    "PatternStatusTransition",
    "PatternType",
    "SuccessPattern",
    "TransitionActionKind",
    "WeeklyGuardKind",
    "WeeklyReflection",
    "WeeklyReflectionPolicy",
    "WeeklySampleGuard",
    "build_weekly_reflection",
    "SQLiteWeeklyReflectionStore",
]
